language: python
sudo: required
python:
- 3.3
- 3.4
- 3.5
cache: pip
branches:
  only:
    - master
    - develop
    - release/*
env:
  global:
    PATH=$HOME:$PATH
install:
- apt-get update
- apt-get install -y sudo
- (wget https://releases.hashicorp.com/terraform/0.9.11/terraform_0.9.11_linux_amd64.zip ; unzip terraform_0.9.11_linux_amd64.zip )
- pip install --upgrade pip
- pip install -r test_requirements.txt
- pip install codecov
before_script:
- make code
script:
- make test
after_success:
- codecov