language: python
sudo: required
python:
- "3.2"
- "3.3"
- "3.4"
- "3.5"
- "3.6"
- "pypy3-5.7"
cache: pip
branches:
  only:
  - master
  - develop
install:
- (wget https://releases.hashicorp.com/terraform/0.9.11/terraform_0.9.11_linux_amd64.zip ; unzip terraform_0.9.11_linux_amd64.zip ; sudo install -m 755 terraform /usr/local/bin/terraform)
- pip install -r test_requirements.txt
- pip install codecov
before_script:
- make code
script:
- make test
after_success:
- codecov
